import { GroqClient } from "../../atlas-kernel/Groq/GroqClient";
import { TaskPlanner } from "../../atlas-planning/TaskPlanner/TaskPlanner";

const mockGenerate = jest.fn();
jest.mock("../../atlas-kernel/Groq/GroqClient", () => ({
  GroqClient: {
    getInstance: jest.fn(() => ({
      generate: mockGenerate,
    })),
  },
}));

let mockCounter = 0;
jest.mock("../../atlas-kernel/utils/uuid", () => ({
  uuidv4: jest.fn(() => {
    mockCounter++;
    return `00000000-0000-4000-8000-${String(mockCounter).padStart(12, "0")}`;
  }),
}));

import { uuidv4 } from "../../atlas-kernel/utils/uuid";

describe("TaskPlanner", () => {
  let planner: TaskPlanner;

  beforeEach(() => {
    planner = new TaskPlanner();
    jest.clearAllMocks();
    mockCounter = 0;
    mockGenerate.mockResolvedValue(
      '["Move forward", "Scan surroundings", "Report findings"]',
    );
  });

  describe("generateTasks", () => {
    it("returns an array of tasks when called without a goal", async () => {
      const tasks = await planner.generateTasks();
      expect(tasks.length).toBeGreaterThanOrEqual(2);
    });

    it("returns an array of tasks when called with a goal", async () => {
      const tasks = await planner.generateTasks("Navigate to waypoint A");
      expect(tasks.length).toBeGreaterThanOrEqual(2);
    });

    it("each task has required fields", async () => {
      const tasks = await planner.generateTasks();

      for (const task of tasks) {
        expect(task.id).toEqual(expect.any(String));
        expect(task.name).toEqual(expect.any(String));
        expect(task.status).toBe("pending");
        expect(typeof task.run).toBe("function");
      }
    });

    it("each task receives a unique id (generated by uuidv4)", async () => {
      (uuidv4 as jest.Mock)
        .mockReturnValueOnce("aaa")
        .mockReturnValueOnce("bbb");

      const tasks = await planner.generateTasks();
      expect(tasks[0].id).toBe("aaa");
      expect(tasks[1].id).toBe("bbb");
    });

    it("tasks have an async run method that does not throw", async () => {
      const tasks = await planner.generateTasks();
      for (const task of tasks) {
        await expect(task.run()).resolves.toBeUndefined();
      }
    });

    it("generates fresh task instances on each call", async () => {
      const first = await planner.generateTasks();
      const second = await planner.generateTasks();
      expect(first[0].id).not.toBe(second[0].id);
      expect(first[1].id).not.toBe(second[1].id);
    });

    it("falls back to defaults when Groq fails", async () => {
      mockGenerate.mockRejectedValue(new Error("API error"));
      const tasks = await planner.generateTasks();
      expect(tasks).toHaveLength(2);
      expect(tasks[0].name).toBe("Move forward");
      expect(tasks[1].name).toBe("Scan surroundings");
    });
  });
});
