import { TaskPlanner } from "../../atlas-planning/TaskPlanner/TaskPlanner";

// Mock uuid so we can verify IDs are generated
let mockCounter = 0;
jest.mock("../../atlas-kernel/utils/uuid", () => ({
  uuidv4: jest.fn(() => {
    mockCounter++;
    return `00000000-0000-4000-8000-${String(mockCounter).padStart(12, "0")}`;
  }),
}));

import { uuidv4 } from "../../atlas-kernel/utils/uuid";

describe("TaskPlanner", () => {
  let planner: TaskPlanner;

  beforeEach(() => {
    planner = new TaskPlanner();
    jest.clearAllMocks();
    mockCounter = 0;
  });

  describe("generateTasks", () => {
    it("returns an array of two tasks when called without a goal", () => {
      const tasks = planner.generateTasks();
      expect(tasks).toHaveLength(2);
    });

    it("returns an array of two tasks when called with a goal", () => {
      const tasks = planner.generateTasks("Navigate to waypoint A");
      expect(tasks).toHaveLength(2);
    });

    it("each task has required fields", () => {
      const [move, scan] = planner.generateTasks();

      expect(move.id).toEqual(expect.any(String));
      expect(move.name).toBe("Move forward");
      expect(move.status).toBe("pending");
      expect(typeof move.run).toBe("function");

      expect(scan.id).toEqual(expect.any(String));
      expect(scan.name).toBe("Scan surroundings");
      expect(scan.status).toBe("pending");
      expect(typeof scan.run).toBe("function");
    });

    it("each task receives a unique id (generated by uuidv4)", () => {
      (uuidv4 as jest.Mock)
        .mockReturnValueOnce("aaa")
        .mockReturnValueOnce("bbb");

      const [move, scan] = planner.generateTasks();
      expect(move.id).toBe("aaa");
      expect(scan.id).toBe("bbb");
    });

    it("tasks have an async run method that does not throw", async () => {
      const [move, scan] = planner.generateTasks();
      await expect(move.run()).resolves.toBeUndefined();
      await expect(scan.run()).resolves.toBeUndefined();
    });

    it("generates fresh task instances on each call", () => {
      const first = planner.generateTasks();
      const second = planner.generateTasks();
      expect(first[0].id).not.toBe(second[0].id);
      expect(first[1].id).not.toBe(second[1].id);
    });
  });
});
